# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoordinatorExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoordinatorExample
  pod 'Coordinator', :path => '../../'

  pod 'ModuleLauncher',
    :git => 'https://github.com/skibinalexander/ModuleLauncher.git/',
    :tag => '1.0.0'

  pod 'PanModal'

end
